[package]
name = "bank_project"
version = "0.1.0"
authors = ["Neisvestny <neisvest.y@gmail.com>"] # авторы проекта
edition = "2021"
readme = "README.md" # путь к файлу README.md
repository = "https://github.com/Neisvestny/bank_project" # URL на GitHub проект

[dependencies]
